### ISSUE TITLE
'run' isn't configured in the .replit file

### ISSUE THREAD

**Issue by todokku** [w-henderson/FreeTube#4]
Hi William ,

1. after import repo to repl.it & run main.py giving error below at the end :
'run' isn't configured in the .replit file
try adding 'run = "echo hello word"' to .replit

2. how to make id code verify for my cloned version ?

3. please give me id code for access on https://freetube.cooltomato.repl.co/
my email is : pushhub@protonmail.com

waiting for your response
finest regards
goodbye

**Comment by w-henderson** [comment]
I haven't used repl.it's "import from GitHub" feature myself, but I believe it's in beta and likely pretty buggy. You could try adding `run=python3 main.py` or something along those lines to the `.replit` file as it suggests. Finally, as for the verification, I'll get back to you by email, but you should be able to figure it out in the code (it's not hard coded but the algorithm to find it is there). The whole point of the verification is so non-developers can't access it.

**Comment by todokku** [comment]
Hi William ,

at the first thank for your help , i can make my own build at : https://freetube--todokku.repl.co/
only my last question is , how to make my own verification id for access on my own build ?

waiting for your response
finest regards
goodbye

**Comment by w-henderson** [comment]
If you've just cloned this repo, then the algorithm to calculate the verification ID will be the same as explained in my email.

**Comment by todokku** [comment]
how to always run without going to sleep idle my repl ?

**Comment by w-henderson** [comment]
That's not something that repl.it currently allows with web repls which require a server-side application. In short, you can't.

**Comment by todokku** [comment]
whats your time zone gmt for caculate ?

**Comment by w-henderson** [comment]
It uses local time, so whatever timezone the client is in.

**Comment by todokku** [comment]
allways show me error in searches : 
Uh oh, looks like an error has occured.
The error code for this error was 404, meaning that the page you were looking for wasn't found. You may have spelt something wrong in the address bar if you manually copied a link. Check the address and try again. If that fails, make sure to contact the developer.
how to solve it ?

**Comment by w-henderson** [comment]
As the error message says, you typed something wrong or made a mistake changing the code. Did you get the error clicking an in-app link?

**Comment by todokku** [comment]
yeah , get errors in-app link & test on your own build too .

**Comment by w-henderson** [comment]
Can you give me some more information? I just tested it myself and it didn't give me an error.

**Comment by todokku** [comment]
im test it on mozilla forefox with my own ip

**Comment by w-henderson** [comment]
What exactly did you test?

**Comment by todokku** [comment]
all my search query get the same error (404/500)

**Comment by w-henderson** [comment]
You just specified two different errors... What exactly did you search?

**Comment by todokku** [comment]
all my text query after show 20 result & in-app link section get error , same for direct url input & other socials exist in app

**Comment by todokku** [comment]
its problem of your code , thanks at all

**Comment by w-henderson** [comment]
I'm working on a fix

**Comment by w-henderson** [comment]
I don't have a lot of time, if possible can you have a go at it?

**Comment by w-henderson** [comment]
@todokku I know it's been a while (I've been busy) but I believe I've finally fixed the issue!
