### ISSUE TITLE
Dont give up and page just refreshes when putting in a url or word

### ISSUE THREAD

**Issue by Hacker1254** [w-henderson/FreeTube#5]
its just refreshes

**Comment by w-henderson** [comment]
Thank you for bringing this to my attention! I've fixed this bug in [the latest commit](https://github.com/w-henderson/FreeTube/commit/16b429e78952ed32e25d4df3f38a9ea0317944db) by updating [my YouTube search library](https://github.com/w-henderson/Unlimited-YouTube-Search). Please give it another go and let me know if it's now working for you!

**Comment by Hacker1254** [comment]
Thank you :0 :)
